/**
 * Tasklet 7.7: Package Assembly Engine
 * Assembles multi-document output bundles into a consolidated master document
 * or multi-file archive.
 * Includes the stated omissions block: what was not produced, and why, travels with what was.
 */

export class IncompleteBundleCannotAssembleError extends Error {
  constructor(message = 'Cannot assemble package: one or more mandatory outputs are still processing') {
    super(message);
    this.name = 'INCOMPLETE_BUNDLE_CANNOT_ASSEMBLE';
  }
}

export class PackageAssemblyEngine {
  constructor(documentLayoutEngine = null) {
    this.documentLayoutEngine = documentLayoutEngine;
  }

  assembleBundlePackage(bundlePlan) {
    if (!bundlePlan) throw new Error('Bundle plan is required');

    const outputs = bundlePlan.outputs || [];
    const omissions = bundlePlan.stated_omissions || bundlePlan.omissions || [];

    // Verify all outputs are completed
    const pending = outputs.filter(o => o.status === 'PROCESSING' || o.status === 'PENDING');
    if (pending.length > 0) {
      throw new IncompleteBundleCannotAssembleError(`Outputs still processing: ${pending.map(p => p.id || p.output_id).join(', ')}`);
    }

    // Generate Table of Contents
    const toc = outputs.map((out, idx) => ({
      index: idx + 1,
      title: out.title || `Output ${idx + 1}`,
      template_id: out.template_id || 'T1',
      page_offset: (idx * 2) + 1,
    }));

    // Build consolidated HTML package
    const tocRowsHtml = toc.map(t => `
      <tr>
        <td style="white-space:nowrap;">${t.index}</td>
        <td><strong>${t.title}</strong> (${t.template_id})</td>
        <td style="white-space:nowrap; text-align:right;">Page ${t.page_offset}</td>
      </tr>
    `).join('');

    const omissionsRowsHtml = omissions.map(o => `
      <tr>
        <td style="white-space:nowrap;"><strong>${o.output_id || 'OUT'}</strong></td>
        <td>${o.title || o.name || 'Deliverable'}</td>
        <td><span class="gate-tag">${o.gate || 'EVIDENCE_SUFFICIENCY'}</span></td>
        <td>${o.reason || 'Insufficient evidentiary basis in transcript'}</td>
      </tr>
    `).join('');

    const omissionsBlockHtml = omissions.length ? `
    <div class="bundle-omissions-container" style="page-break-after: always; margin-bottom: 30px;">
      <h2 class="section-title">Stated Omissions Block</h2>
      <p><em>What was not produced, and why, travels with what was. Concludo declines to produce deliverables unsupported by the evidentiary record.</em></p>
      <table class="concludo-table omissions-table">
        <thead>
          <tr>
            <th style="white-space:nowrap;">ID</th>
            <th>Deliverable Name</th>
            <th>Gate Withheld</th>
            <th>Reason Stated</th>
          </tr>
        </thead>
        <tbody>
          ${omissionsRowsHtml}
        </tbody>
      </table>
    </div>` : '';

    const bundleHtml = `<!DOCTYPE html>
<html lang="en-AU">
<head>
  <meta charset="utf-8">
  <title>Consolidated Meeting Intelligence Package</title>
  <style>
    body { font-family: 'Inter', sans-serif; color: #16263F; margin: 0; padding: 20px; }
    .concludo-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    .concludo-table th { background: #16263F; color: #fff; padding: 8px 10px; text-align: left; }
    .concludo-table td { padding: 8px 10px; border-bottom: 1px solid #E0E4EC; }
    .section-title { font-family: 'Poppins', sans-serif; border-bottom: 2px solid #E2B53C; padding-bottom: 6px; }
    .gate-tag { background: #FEE2E2; color: #991B1B; padding: 2px 6px; border-radius: 3px; font-weight: 600; font-size: 11px; }
  </style>
</head>
<body>
  <div class="bundle-cover" style="page-break-after: always; padding: 40px 0; text-align: center;">
    <h1 style="font-size: 32px; font-family: 'Poppins', sans-serif;">Consolidated Intelligence Package</h1>
    <p style="font-size: 16px; color: #666;">Generated by Concludo Workspace</p>
  </div>

  <div class="bundle-toc" style="page-break-after: always; margin-bottom: 30px;">
    <h2 class="section-title">Table of Contents</h2>
    <table class="concludo-table toc-table">
      <thead>
        <tr>
          <th style="white-space:nowrap;">#</th>
          <th>Deliverable</th>
          <th style="text-align:right;">Starts at</th>
        </tr>
      </thead>
      <tbody>
        ${tocRowsHtml}
      </tbody>
    </table>
  </div>

  ${omissionsBlockHtml}

  <div class="bundle-content">
    ${outputs.map((out, i) => `
      <div class="bundle-sheet" id="sheet-${i + 1}" style="page-break-before: always;">
        <h2 style="font-family: 'Poppins', sans-serif; color: #21395C;">Deliverable ${i + 1}: ${out.title || 'Report'}</h2>
        <div>${out.rendered_html || `<p>${out.summary || 'Compiled document content.'}</p>`}</div>
      </div>
    `).join('')}
  </div>
</body>
</html>`;

    return {
      tableOfContents: toc,
      omissionsCount: omissions.length,
      assembledHtml: bundleHtml,
    };
  }
}
