/**
 * Concludo Extensible Connector & Manifest Registry
 * Conforms to Master Build Instruction Sections 5, 6, 7
 */

export interface TriggerManifest {
  revocationOperation?: any;
  deprecationState?: any;
  errorMapping?: any;
  pagination?: any;
  inputAndOutputSchemas?: any;
  iconReference?: string;
  key: string;
  version: string;
  displayName: string;
  description: string;
  category: 'meetings' | 'projects' | 'system' | 'integrations' | 'governance';
  sourceService: string;
  event: string;
  configurationSchema: Record<string, any>;
  payloadSchema: Record<string, any>;
  permissions: string[];
  deduplicationGuidance: string;
  replayPolicy: 'allowed' | 'idempotent_only' | 'rejected';
  backfillSupport: boolean;
  expectedVolume: 'low' | 'medium' | 'high';
  icon?: string;
  connectionRequirement?: string;
  availabilityState: 'available' | 'beta' | 'deprecated';
}

export interface ActionManifest {
  revocationOperation?: any;
  deprecationState?: any;
  errorMapping?: any;
  pagination?: any;
  inputAndOutputSchemas?: any;
  iconReference?: string;
  key: string;
  version: string;
  displayName: string;
  description: string;
  category: 'logic' | 'governance' | 'ai_agents' | 'projects' | 'calendar' | 'communications' | 'integrations';
  application: string;
  inputSchema: Record<string, any>;
  outputSchema: Record<string, any>;
  configurationSchema: Record<string, any>;
  requiredPermissions: string[];
  requiredConnection?: string;
  riskClassification: 'low' | 'medium' | 'high' | 'critical';
  defaultApprovalPolicy: { required: boolean; approverRole?: string };
  defaultTimeoutSeconds: number;
  defaultRetryPolicy: { maxAttempts: number; initialIntervalMs: number; backoffFactor: number };
  idempotencyCapability: boolean;
  compensationCapability: boolean;
  icon?: string;
  availabilityState: 'available' | 'beta' | 'deprecated';
}

export interface ConnectorManifest {
  availabilityState?: string;
  paginationSupport?: boolean;
  connectorKey: string;
  version: string;
  displayName: string;
  description: string;
  category: 'workspace_native' | 'communication' | 'productivity' | 'crm' | 'developer' | 'meetings' | 'governance' | 'integrations';
  iconReference: string;
  authenticationType: 'session' | 'oauth2' | 'api_key' | 'webhook_signature' | 'bearer' | 'webhook_hmac';
  requiredScopes: string[];
  triggers: string[];
  actions: string[];
  inputAndOutputSchemas: Record<string, any>;
  webhookSupport: boolean;
  rateLimits: { requestsPerMinute?: number; requestsPerSecond?: number; burst?: number; burstLimit?: number };
  pagination: { supported: boolean; type?: 'cursor' | 'offset' };
  retryGuidance: { maxAttempts: number; statusCodesToRetry: number[] } | string;
  errorMapping: Record<string, string>;
  testConnectionOperation: string;
  healthCheckOperation: string;
  secretReferences: string[];
  revocationOperation: string;
  deprecationState: 'active' | 'deprecated' | 'sunset';
}

// 1. Initial Triggers Registry (Section 5)
export const TRIGGER_MANIFESTS: Record<string, TriggerManifest> = {
  'manual.started': {
    key: 'manual.started',
    version: '1.0.0',
    displayName: 'Manual Run Started',
    description: 'Triggered manually by an authorised operator from the workspace.',
    category: 'system',
    sourceService: 'concludo_system',
    event: 'manual.started',
    configurationSchema: {},
    payloadSchema: { userId: 'string', initiatedAt: 'string' },
    permissions: ['workflow:execute'],
    deduplicationGuidance: 'Explicit user click generates unique run ID.',
    replayPolicy: 'allowed',
    backfillSupport: false,
    expectedVolume: 'low',
    icon: 'PlayCircle',
    availabilityState: 'available',
  },
  'schedule.reached': {
    key: 'schedule.reached',
    version: '1.0.0',
    displayName: 'Schedule Reached',
    description: 'Triggered on a recurring cron or interval schedule in Melbourne time.',
    category: 'system',
    sourceService: 'concludo_scheduler',
    event: 'schedule.reached',
    configurationSchema: { cronExpression: 'string', timezone: 'string' },
    payloadSchema: { scheduledFor: 'string' },
    permissions: ['workflow:schedule'],
    deduplicationGuidance: 'Scoped to slot timestamp window.',
    replayPolicy: 'idempotent_only',
    backfillSupport: true,
    expectedVolume: 'medium',
    icon: 'Clock',
    availabilityState: 'available',
  },
  'webhook.received': {
    key: 'webhook.received',
    version: '1.0.0',
    displayName: 'Webhook Received',
    description: 'Triggered when an authenticated inbound HMAC webhook payload arrives.',
    category: 'integrations',
    sourceService: 'concludo_webhooks',
    event: 'webhook.received',
    configurationSchema: { endpointPath: 'string', secretKeyRef: 'string' },
    payloadSchema: { headers: 'object', rawBody: 'string', parsedJson: 'object' },
    permissions: ['webhooks:receive'],
    deduplicationGuidance: 'X-Concludo-Delivery-ID idempotency key.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'high',
    iconReference: 'Webhook', inputAndOutputSchemas: {}, pagination: { supported: false }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
    availabilityState: 'available',
  },
  'api.event_received': {
    key: 'api.event_received',
    version: '1.0.0',
    displayName: 'Public API Event Received',
    description: 'Inbound authenticated event pushed via Concludo Public API.',
    category: 'integrations',
    sourceService: 'concludo_public_api',
    event: 'api.event_received',
    configurationSchema: { eventName: 'string' },
    payloadSchema: { clientEventId: 'string', payload: 'object' },
    permissions: ['api:events:write'],
    deduplicationGuidance: 'clientEventId uniqueness check.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'medium',
    icon: 'Code',
    availabilityState: 'available',
  },
  'meeting.completed': {
    key: 'meeting.completed',
    version: '1.0.0',
    displayName: 'Meeting Completed',
    description: 'Fired when a meeting finishes and transcript/audio ingestion finishes.',
    category: 'meetings',
    sourceService: 'concludo_meetings',
    event: 'meeting.completed',
    configurationSchema: { meetingTypes: 'array', minDurationMinutes: 'number' },
    payloadSchema: {
      organisationId: 'string',
      meetingId: 'string',
      meetingTitle: 'string',
      completedAt: 'string',
      transcriptRef: 'string',
      projectId: 'string?',
      projectOwnerId: 'string?',
    },
    permissions: ['meetings:read'],
    deduplicationGuidance: 'Scoped to organisationId + meetingId.',
    replayPolicy: 'idempotent_only',
    backfillSupport: true,
    expectedVolume: 'high',
    icon: 'Video',
    availabilityState: 'available',
  },
  'document_reader.completed': {
    key: 'document_reader.completed',
    version: '1.0.0',
    displayName: 'Document Processing Completed',
    description: 'Triggered when Concludo Document Reader finishes parsing a PDF/DOCX file.',
    category: 'system',
    sourceService: 'concludo_document_reader',
    event: 'document_reader.completed',
    configurationSchema: { fileTypes: 'array' },
    payloadSchema: { fileId: 'string', filename: 'string', extractedText: 'string' },
    permissions: ['documents:read'],
    deduplicationGuidance: 'Scoped to document ID and version.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'medium',
    icon: 'FileText',
    availabilityState: 'available',
  },
  'approval.completed': {
    key: 'approval.completed',
    version: '1.0.0',
    displayName: 'Approval Completed',
    description: 'Triggered when an approval request in Approval Centre is resolved.',
    category: 'governance',
    sourceService: 'concludo_approval_centre',
    event: 'approval.completed',
    configurationSchema: { approvalType: 'string' },
    payloadSchema: { approvalId: 'string', decision: 'string', approverId: 'string', notes: 'string' },
    permissions: ['approvals:read'],
    deduplicationGuidance: 'Scoped to approvalId.',
    replayPolicy: 'rejected',
    backfillSupport: false,
    expectedVolume: 'medium',
    icon: 'CheckSquare',
    availabilityState: 'available',
  },
  'project.created': {
    key: 'project.created',
    version: '1.0.0',
    displayName: 'Project Created',
    description: 'Fired when a new project is created in Concludo Projects.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'project.created',
    configurationSchema: {},
    payloadSchema: { projectId: 'string', title: 'string', ownerId: 'string' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Scoped to projectId.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'medium',
    icon: 'FolderPlus',
    availabilityState: 'available',
  },
  'task.created': {
    key: 'task.created',
    version: '1.0.0',
    displayName: 'Task Created',
    description: 'Fired when a task is created within a project.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'task.created',
    configurationSchema: { projectId: 'string?' },
    payloadSchema: { taskId: 'string', title: 'string', assigneeId: 'string', dueDate: 'string' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Scoped to taskId.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'high',
    icon: 'CheckCircle2',
    availabilityState: 'available',
  },
  'task.completed': {
    key: 'task.completed',
    version: '1.0.0',
    displayName: 'Task Completed',
    description: 'Fired when a task is marked complete in Concludo Projects.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'task.completed',
    configurationSchema: {},
    payloadSchema: { taskId: 'string', completedAt: 'string', completedBy: 'string' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Scoped to taskId + completion timestamp.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'high',
    icon: 'CheckCircle',
    availabilityState: 'available',
  },
  'task.overdue': {
    key: 'task.overdue',
    version: '1.0.0',
    displayName: 'Task Overdue',
    description: 'Fired when an active task crosses its due date without completion.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'task.overdue',
    configurationSchema: {},
    payloadSchema: { taskId: 'string', dueDate: 'string', overdueDays: 'number' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Daily rate-limited per taskId.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'medium',
    icon: 'AlertTriangle',
    availabilityState: 'available',
  },
  'milestone.approaching': {
    key: 'milestone.approaching',
    version: '1.0.0',
    displayName: 'Milestone Approaching',
    description: 'Fired 7 days and 48 hours prior to milestone target delivery.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'milestone.approaching',
    configurationSchema: { warningDays: 'number' },
    payloadSchema: { milestoneId: 'string', targetDate: 'string' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Unique per milestone warning interval.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'low',
    icon: 'Flag',
    availabilityState: 'available',
  },
  'milestone.delayed': {
    key: 'milestone.delayed',
    version: '1.0.0',
    displayName: 'Milestone Delayed',
    description: 'Fired when milestone target date is pushed back or overdue.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'milestone.delayed',
    configurationSchema: {},
    payloadSchema: { milestoneId: 'string', originalDate: 'string', newDate: 'string' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Unique per milestone update.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'low',
    icon: 'AlertOctagon',
    availabilityState: 'available',
  },
  'risk.created': {
    key: 'risk.created',
    version: '1.0.0',
    displayName: 'Risk Logged',
    description: 'Fired when a strategic risk item is registered in project risk register.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'risk.created',
    configurationSchema: { minSeverity: 'string' },
    payloadSchema: { riskId: 'string', severity: 'string', title: 'string' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Unique per riskId.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'low',
    icon: 'ShieldAlert',
    availabilityState: 'available',
  },
  'risk.rating_changed': {
    key: 'risk.rating_changed',
    version: '1.0.0',
    displayName: 'Risk Rating Changed',
    description: 'Fired when risk likelihood or impact score escalates.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'risk.rating_changed',
    configurationSchema: {},
    payloadSchema: { riskId: 'string', oldRating: 'string', newRating: 'string' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Unique per risk update.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'low',
    icon: 'TrendingUp',
    availabilityState: 'available',
  },
  'issue.created': {
    key: 'issue.created',
    version: '1.0.0',
    displayName: 'Issue Created',
    description: 'Fired when an operational blocker or defect is logged.',
    category: 'projects',
    sourceService: 'concludo_projects',
    event: 'issue.created',
    configurationSchema: {},
    payloadSchema: { issueId: 'string', priority: 'string', title: 'string' },
    permissions: ['projects:read'],
    deduplicationGuidance: 'Unique per issueId.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'medium',
    icon: 'AlertCircle',
    availabilityState: 'available',
  },
  'workflow.completed': {
    key: 'workflow.completed',
    version: '1.0.0',
    displayName: 'Workflow Execution Completed',
    description: 'Fired when an upstream workflow completes all steps successfully.',
    category: 'system',
    sourceService: 'concludo_workflows',
    event: 'workflow.completed',
    configurationSchema: { workflowKey: 'string' },
    payloadSchema: { runId: 'string', workflowKey: 'string', durationMs: 'number' },
    permissions: ['workflow:read'],
    deduplicationGuidance: 'Unique per runId.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'medium',
    icon: 'Workflow',
    availabilityState: 'available',
  },
  'workflow.failed': {
    key: 'workflow.failed',
    version: '1.0.0',
    displayName: 'Workflow Execution Failed',
    description: 'Fired when an upstream workflow exhausts retries and fails.',
    category: 'system',
    sourceService: 'concludo_workflows',
    event: 'workflow.failed',
    configurationSchema: { workflowKey: 'string' },
    payloadSchema: { runId: 'string', workflowKey: 'string', errorMessage: 'string', incidentId: 'string?' },
    permissions: ['workflow:read'],
    deduplicationGuidance: 'Unique per runId.',
    replayPolicy: 'idempotent_only',
    backfillSupport: false,
    expectedVolume: 'low',
    icon: 'XCircle',
    availabilityState: 'available',
  },
};

// 2. Initial Action Registry (Section 6)
export const ACTION_MANIFESTS: Record<string, ActionManifest> = {
  // LOGIC
  validate_data: {
    key: 'validate_data',
    version: '1.0.0',
    displayName: 'Validate Data',
    description: 'Validates input payload against a JSON schema or constraint rules.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { data: 'object', rules: 'object' },
    outputSchema: { isValid: 'boolean', errors: 'array' },
    configurationSchema: { haltOnFailure: 'boolean' },
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'ShieldCheck',
    availabilityState: 'available',
  },
  evaluate_condition: {
    key: 'evaluate_condition',
    version: '1.0.0',
    displayName: 'Evaluate Condition',
    description: 'Evaluates logical expression to route workflow execution branches.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { left: 'any', operator: 'string', right: 'any' },
    outputSchema: { match: 'boolean' },
    configurationSchema: {},
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 15,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'GitFork',
    availabilityState: 'available',
  },
  branch: {
    key: 'branch',
    version: '1.0.0',
    displayName: 'Branch',
    description: 'Splits workflow into multiple conditional execution paths.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { conditionResult: 'boolean' },
    outputSchema: { selectedBranch: 'string' },
    configurationSchema: { branches: 'array' },
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 10,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Split',
    availabilityState: 'available',
  },
  merge: {
    key: 'merge',
    version: '1.0.0',
    displayName: 'Merge Branches',
    description: 'Rejoins parallel or branched execution paths before proceeding.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { branchOutputs: 'array' },
    outputSchema: { unifiedResult: 'object' },
    configurationSchema: { strategy: 'string' },
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 15,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'GitMerge',
    availabilityState: 'available',
  },
  bounded_loop: {
    key: 'bounded_loop',
    version: '1.0.0',
    displayName: 'Bounded Loop',
    description: 'Iterates over an array with strict maximum iteration guardrails (max 50).',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { items: 'array' },
    outputSchema: { processedCount: 'number', itemsOut: 'array' },
    configurationSchema: { maxIterations: 'number' },
    requiredPermissions: [],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 180,
    defaultRetryPolicy: { maxAttempts: 2, initialIntervalMs: 2000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Repeat',
    availabilityState: 'available',
  },
  wait: {
    key: 'wait',
    version: '1.0.0',
    displayName: 'Wait Duration',
    description: 'Suspends workflow run for a specified duration in seconds or hours.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { durationSeconds: 'number' },
    outputSchema: { resumedAt: 'string' },
    configurationSchema: { maxWaitDays: 'number' },
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 86400,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Hourglass',
    availabilityState: 'available',
  },
  delay_until: {
    key: 'delay_until',
    version: '1.0.0',
    displayName: 'Delay Until Timestamp',
    description: 'Pauses workflow until a specific UTC/Melbourne timestamp is reached.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { targetTimestamp: 'string' },
    outputSchema: { resumedAt: 'string' },
    configurationSchema: {},
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 86400 * 30,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'CalendarClock',
    availabilityState: 'available',
  },
  transform_data: {
    key: 'transform_data',
    version: '1.0.0',
    displayName: 'Transform Data',
    description: 'Transforms JSON data fields according to strict declarative mapping.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { source: 'object', template: 'object' },
    outputSchema: { transformed: 'object' },
    configurationSchema: {},
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 15,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'ArrowRightLeft',
    availabilityState: 'available',
  },
  set_variable: {
    key: 'set_variable',
    version: '1.0.0',
    displayName: 'Set Workflow Variable',
    description: 'Stores or updates a workflow variable in execution context.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { variableName: 'string', value: 'any' },
    outputSchema: { updated: 'boolean' },
    configurationSchema: {},
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 10,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Variable',
    availabilityState: 'available',
  },
  end: {
    key: 'end',
    version: '1.0.0',
    displayName: 'End Workflow',
    description: 'Explicit terminal step completing the workflow execution run.',
    category: 'logic',
    application: 'concludo_logic',
    inputSchema: { finalStatus: 'string', summary: 'string' },
    outputSchema: { completed: 'boolean' },
    configurationSchema: {},
    requiredPermissions: [],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 10,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'CheckCircle',
    availabilityState: 'available',
  },

  // GOVERNANCE
  request_approval: {
    key: 'request_approval',
    version: '1.0.0',
    displayName: 'Request Human Approval',
    description: 'Enforces human-in-the-loop sign-off in Concludo Approval Centre.',
    category: 'governance',
    application: 'concludo_approval_centre',
    inputSchema: { subject: 'string', previewData: 'object', approverRole: 'string', dueHours: 'number' },
    outputSchema: { approvalId: 'string', decision: 'string', approverId: 'string', approvedPayload: 'object' },
    configurationSchema: { allowInlineEdits: 'boolean' },
    requiredPermissions: ['approvals:create'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 86400 * 7,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 1000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'UserCheck',
    availabilityState: 'available',
  },
  create_manual_review: {
    key: 'create_manual_review',
    version: '1.0.0',
    displayName: 'Create Manual Review Task',
    description: 'Assigns an administrative triage review when missing required context.',
    category: 'governance',
    application: 'concludo_governance',
    inputSchema: { reason: 'string', candidateItems: 'array' },
    outputSchema: { reviewTaskId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['governance:review'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 60,
    defaultRetryPolicy: { maxAttempts: 2, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'ClipboardList',
    availabilityState: 'available',
  },
  create_incident: {
    key: 'create_incident',
    version: '1.0.0',
    displayName: 'Create Workflow Incident',
    description: 'Registers an incident upon 3 consecutive retries or critical fault.',
    category: 'governance',
    application: 'concludo_governance',
    inputSchema: { workflowKey: 'string', stepKey: 'string', errorMessage: 'string', contextData: 'object' },
    outputSchema: { incidentId: 'string', severity: 'string' },
    configurationSchema: { severity: 'string' },
    requiredPermissions: ['incidents:create'],
    riskClassification: 'high',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 60,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'AlertOctagon',
    availabilityState: 'available',
  },
  record_audit_event: {
    key: 'record_audit_event',
    version: '1.0.0',
    displayName: 'Record Audit Event',
    description: 'Writes an immutable compliance audit record to enterprise audit log.',
    category: 'governance',
    application: 'concludo_enterprise',
    inputSchema: { action: 'string', entityType: 'string', entityId: 'string', details: 'object' },
    outputSchema: { auditId: 'string', recordedAt: 'string' },
    configurationSchema: {},
    requiredPermissions: ['audit:write'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'FileCheck',
    availabilityState: 'available',
  },

  // AI AGENTS
  invoke_ai_agent: {
    key: 'invoke_ai_agent',
    version: '1.0.0',
    displayName: 'Invoke AI Agent',
    description: 'Runs an authorised Concludo AI Agent with strict structured schema validation.',
    category: 'ai_agents',
    application: 'concludo_ai_agents',
    inputSchema: { agentType: 'string', parameters: 'object' },
    outputSchema: { structuredResult: 'object', executionDurationMs: 'number' },
    configurationSchema: { modelTier: 'string', temperature: 'number' },
    requiredPermissions: ['agents:execute'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 120,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 2000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Bot',
    availabilityState: 'available',
  },
  summarise_meeting: {
    key: 'summarise_meeting',
    version: '1.0.0',
    displayName: 'Summarise Meeting',
    description: 'Generates evidence-grounded summary from transcript without inventing facts.',
    category: 'ai_agents',
    application: 'concludo_ai_agents',
    inputSchema: { meetingTitle: 'string', transcript: 'string' },
    outputSchema: { summary: 'string', keyPoints: 'array', sourceReferences: 'array' },
    configurationSchema: {},
    requiredPermissions: ['agents:execute'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 90,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 2000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Sparkles',
    availabilityState: 'available',
  },
  extract_meeting_actions: {
    key: 'extract_meeting_actions',
    version: '1.0.0',
    displayName: 'Extract Meeting Actions',
    description: 'Extracts action tasks, owners, and due dates tied directly to transcript citations.',
    category: 'ai_agents',
    application: 'concludo_ai_agents',
    inputSchema: { transcript: 'string', meetingTitle: 'string' },
    outputSchema: { actions: 'array' },
    configurationSchema: { requireVerbatimQuote: 'boolean' },
    requiredPermissions: ['agents:execute'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 90,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 2000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'ListFilter',
    availabilityState: 'available',
  },
  analyse_document: {
    key: 'analyse_document',
    version: '1.0.0',
    displayName: 'Analyse Document',
    description: 'Extracts structured information from attached PDF/DOCX files.',
    category: 'ai_agents',
    application: 'concludo_ai_agents',
    inputSchema: { documentText: 'string' },
    outputSchema: { extractedEntities: 'object', summary: 'string' },
    configurationSchema: {},
    requiredPermissions: ['agents:execute'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 120,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 2000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'FileSearch',
    availabilityState: 'available',
  },
  generate_structured_draft: {
    key: 'generate_structured_draft',
    version: '1.0.0',
    displayName: 'Generate Structured Draft',
    description: 'Synthesizes formatted output drafts adhering to Concludo brand and schema.',
    category: 'ai_agents',
    application: 'concludo_ai_agents',
    inputSchema: { prompt: 'string', schema: 'object' },
    outputSchema: { draftJson: 'object' },
    configurationSchema: {},
    requiredPermissions: ['agents:execute'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 60,
    defaultRetryPolicy: { maxAttempts: 2, initialIntervalMs: 1500, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'FileCode',
    availabilityState: 'available',
  },

  // PROJECTS
  create_project_draft: {
    key: 'create_project_draft',
    version: '1.0.0',
    displayName: 'Create Project Draft',
    description: 'Creates a pending project draft awaiting user confirmation.',
    category: 'projects',
    application: 'concludo_projects',
    inputSchema: { title: 'string', description: 'string', ownerId: 'string' },
    outputSchema: { projectDraftId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['projects:write'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 2, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'Folder',
    availabilityState: 'available',
  },
  create_project: {
    key: 'create_project',
    version: '1.0.0',
    displayName: 'Create Project',
    description: 'Creates a project record in Concludo Projects.',
    category: 'projects',
    application: 'concludo_projects',
    inputSchema: { title: 'string', description: 'string', ownerId: 'string' },
    outputSchema: { projectId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['projects:write'],
    riskClassification: 'high',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'FolderPlus',
    availabilityState: 'available',
  },
  create_task: {
    key: 'create_task',
    version: '1.0.0',
    displayName: 'Create Project Task',
    description: 'Adds an approved action task to an existing Concludo project.',
    category: 'projects',
    application: 'concludo_projects',
    inputSchema: {
      projectId: 'string',
      title: 'string',
      assigneeId: 'string?',
      dueDate: 'string?',
      description: 'string?',
      sourceReference: 'string',
    },
    outputSchema: { taskId: 'string', created: 'boolean' },
    configurationSchema: { deduplicateByTitle: 'boolean' },
    requiredPermissions: ['projects:write'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'CheckSquare',
    availabilityState: 'available',
  },
  create_milestone: {
    key: 'create_milestone',
    version: '1.0.0',
    displayName: 'Create Milestone',
    description: 'Adds a project delivery milestone with target completion date.',
    category: 'projects',
    application: 'concludo_projects',
    inputSchema: { projectId: 'string', title: 'string', targetDate: 'string' },
    outputSchema: { milestoneId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['projects:write'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'Flag',
    availabilityState: 'available',
  },
  create_risk: {
    key: 'create_risk',
    version: '1.0.0',
    displayName: 'Create Risk Item',
    description: 'Registers a risk item in the project risk register.',
    category: 'projects',
    application: 'concludo_projects',
    inputSchema: { projectId: 'string', title: 'string', severity: 'string' },
    outputSchema: { riskId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['projects:write'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'ShieldAlert',
    availabilityState: 'available',
  },
  create_issue: {
    key: 'create_issue',
    version: '1.0.0',
    displayName: 'Create Issue',
    description: 'Logs a known issue or blocker against a project.',
    category: 'projects',
    application: 'concludo_projects',
    inputSchema: { projectId: 'string', title: 'string', priority: 'string' },
    outputSchema: { issueId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['projects:write'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'AlertCircle',
    availabilityState: 'available',
  },
  create_decision: {
    key: 'create_decision',
    version: '1.0.0',
    displayName: 'Create Decision Record',
    description: 'Logs an agreed decision into Concludo Decision Memory.',
    category: 'projects',
    application: 'concludo_projects',
    inputSchema: { projectId: 'string', decisionText: 'string', rationale: 'string' },
    outputSchema: { decisionId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['projects:write'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'BookOpen',
    availabilityState: 'available',
  },
  create_project_status_draft: {
    key: 'create_project_status_draft',
    version: '1.0.0',
    displayName: 'Create Project Status Draft',
    description: 'Creates a drafted status update for project owner sign-off.',
    category: 'projects',
    application: 'concludo_projects',
    inputSchema: { projectId: 'string', status: 'string', highlights: 'array' },
    outputSchema: { updateDraftId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['projects:write'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 2, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Activity',
    availabilityState: 'available',
  },

  // CALENDAR
  create_calendar_draft: {
    key: 'create_calendar_draft',
    version: '1.0.0',
    displayName: 'Create Calendar Draft',
    description: 'Creates a non-mutating calendar item draft for human review and date confirmation.',
    category: 'calendar',
    application: 'concludo_calendar',
    inputSchema: {
      title: 'string',
      date: 'string',
      time: 'string?',
      isAllDay: 'boolean',
      owner: 'string',
      relatedProject: 'string?',
      relatedMeeting: 'string?',
      sourceReference: 'string',
      confidence: 'string',
    },
    outputSchema: { draftId: 'string', reviewRequired: 'boolean' },
    configurationSchema: { requireExplicitConfirmationForInferred: 'boolean' },
    requiredPermissions: ['calendar:read'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 2, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    iconReference: 'Calendar', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
    availabilityState: 'available',
  },
  create_calendar_event: {
    key: 'create_calendar_event',
    version: '1.0.0',
    displayName: 'Create Calendar Event',
    description: 'Inserts an approved event or deadline directly into the Concludo Calendar.',
    category: 'calendar',
    application: 'concludo_calendar',
    inputSchema: {
      title: 'string',
      itemType: 'string',
      startDate: 'string',
      endDate: 'string?',
      startTime: 'string?',
      isAllDay: 'boolean',
      projectId: 'string?',
      outputId: 'string?',
      sourceReference: 'string',
    },
    outputSchema: { calendarItemId: 'string', idempotencyKey: 'string' },
    configurationSchema: { deduplicateByTitleAndDate: 'boolean' },
    requiredPermissions: ['calendar:write'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'CalendarPlus',
    availabilityState: 'available',
  },

  // COMMUNICATIONS
  create_internal_notification: {
    key: 'create_internal_notification',
    version: '1.0.0',
    displayName: 'Create Internal Notification',
    description: 'Sends an in-app workspace notification banner or alert to a member.',
    category: 'communications',
    application: 'concludo_notifications',
    inputSchema: { recipientId: 'string', title: 'string', message: 'string', linkUrl: 'string?' },
    outputSchema: { notificationId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['notifications:send'],
    riskClassification: 'low',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Bell',
    availabilityState: 'available',
  },
  create_external_message_draft: {
    key: 'create_external_message_draft',
    version: '1.0.0',
    displayName: 'Create External Message Draft',
    description: 'Stages a draft message (Teams, Slack, Email) for explicit operator review.',
    category: 'communications',
    application: 'concludo_communications',
    inputSchema: { channel: 'string', destination: 'string', content: 'string' },
    outputSchema: { draftMessageId: 'string' },
    configurationSchema: {},
    requiredPermissions: ['messages:draft'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 30,
    defaultRetryPolicy: { maxAttempts: 2, initialIntervalMs: 1000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    iconReference: 'Mail', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
    availabilityState: 'available',
  },
  send_approved_external_message: {
    key: 'send_approved_external_message',
    version: '1.0.0',
    displayName: 'Send Approved External Message',
    description: 'Dispatches an approved message to a connected integration channel.',
    category: 'communications',
    application: 'concludo_integrations',
    inputSchema: { approvalId: 'string', draftMessageId: 'string' },
    outputSchema: { dispatchedMessageId: 'string', sentAt: 'string' },
    configurationSchema: {},
    requiredPermissions: ['messages:send'],
    requiredConnection: 'any_comm_integration',
    riskClassification: 'high',
    defaultApprovalPolicy: { required: true, approverRole: 'project_owner' },
    defaultTimeoutSeconds: 45,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 2000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Send',
    availabilityState: 'available',
  },

  // INTEGRATIONS
  call_api: {
    key: 'call_api',
    version: '1.0.0',
    displayName: 'Call External API',
    description: 'Executes an HTTPS REST call to an approved endpoint with secret header injection.',
    category: 'integrations',
    application: 'concludo_integrations',
    inputSchema: { method: 'string', endpoint: 'string', body: 'object' },
    outputSchema: { statusCode: 'number', responseData: 'object' },
    configurationSchema: { timeoutMs: 'number', allowedHosts: 'array' },
    requiredPermissions: ['api:call_external'],
    riskClassification: 'high',
    defaultApprovalPolicy: { required: true, approverRole: 'organisation_admin' },
    defaultTimeoutSeconds: 60,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 2000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    iconReference: 'Globe', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
    availabilityState: 'available',
  },
  publish_webhook: {
    key: 'publish_webhook',
    version: '1.0.0',
    displayName: 'Publish Outbound Webhook',
    description: 'Publishes an event payload to a configured subscriber webhook URL.',
    category: 'integrations',
    application: 'concludo_webhooks',
    inputSchema: { webhookUrl: 'string', eventType: 'string', payload: 'object' },
    outputSchema: { deliveryId: 'string', statusCode: 'number' },
    configurationSchema: {},
    requiredPermissions: ['webhooks:publish'],
    riskClassification: 'medium',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 45,
    defaultRetryPolicy: { maxAttempts: 3, initialIntervalMs: 2000, backoffFactor: 2 },
    idempotencyCapability: true,
    compensationCapability: false,
    icon: 'Radio',
    availabilityState: 'available',
  },
  invoke_subworkflow: {
    key: 'invoke_subworkflow',
    version: '1.0.0',
    displayName: 'Invoke Sub-Workflow',
    description: 'Executes a child workflow synchronously or asynchronously.',
    category: 'integrations',
    application: 'concludo_workflows',
    inputSchema: { targetWorkflowKey: 'string', inputs: 'object' },
    outputSchema: { subRunId: 'string', status: 'string', outputs: 'object' },
    configurationSchema: { waitForCompletion: 'boolean' },
    requiredPermissions: ['workflow:execute'],
    riskClassification: 'high',
    defaultApprovalPolicy: { required: false },
    defaultTimeoutSeconds: 300,
    defaultRetryPolicy: { maxAttempts: 1, initialIntervalMs: 2000, backoffFactor: 1 },
    idempotencyCapability: true,
    compensationCapability: true,
    icon: 'Layers',
    availabilityState: 'available',
  },
};

// 3. Extensible Connector Registry (Section 7)
export const CONNECTOR_MANIFESTS: Record<string, ConnectorManifest> = {
  concludo_meetings: {
    connectorKey: 'concludo_meetings',
    version: '1.0.0',
    displayName: 'Concludo Meetings',
    description: 'Native meeting recording, transcript parsing and attendee metadata service.',
    category: 'workspace_native',
    iconReference: 'Video',
    authenticationType: 'session',
    requiredScopes: ['meetings:read', 'transcripts:read'],
    triggers: ['meeting.completed'],
    actions: ['summarise_meeting', 'extract_meeting_actions'],
    inputAndOutputSchemas: {},
    webhookSupport: true,
    rateLimits: { requestsPerMinute: 300, burst: 50 },
    pagination: { supported: true, type: 'cursor' },
    retryGuidance: { maxAttempts: 3, statusCodesToRetry: [429, 500, 502, 503] },
    errorMapping: { NOT_FOUND: 'Meeting record could not be found.' },
    testConnectionOperation: 'pingMeetingsService',
    healthCheckOperation: 'healthCheck',
    secretReferences: [],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_ai_agents: {
    connectorKey: 'concludo_ai_agents',
    version: '1.0.0',
    displayName: 'Concludo AI Agents',
    description: 'Server-side agent intelligence executing structured LLM reasoning and synthesis.',
    category: 'workspace_native',
    iconReference: 'Bot',
    authenticationType: 'session',
    requiredScopes: ['agents:execute'],
    triggers: [],
    actions: ['invoke_ai_agent', 'summarise_meeting', 'extract_meeting_actions', 'analyse_document', 'generate_structured_draft'],
    inputAndOutputSchemas: {},
    webhookSupport: false,
    rateLimits: { requestsPerMinute: 60, burst: 10 },
    pagination: { supported: false },
    retryGuidance: { maxAttempts: 3, statusCodesToRetry: [429, 500, 503, 504] },
    errorMapping: { TIMEOUT: 'AI service request timed out.' },
    testConnectionOperation: 'pingAgentEngine',
    healthCheckOperation: 'healthCheck',
    secretReferences: ['OPENAI_API_KEY', 'ANTHROPIC_API_KEY'],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_approval_centre: {
    connectorKey: 'concludo_approval_centre',
    version: '1.0.0',
    displayName: 'Concludo Approval Centre',
    description: 'Native human-in-the-loop governance sign-off and review portal.',
    category: 'workspace_native',
    iconReference: 'UserCheck',
    authenticationType: 'session',
    requiredScopes: ['approvals:create', 'approvals:read', 'approvals:manage'],
    triggers: ['approval.completed'],
    actions: ['request_approval'],
    inputAndOutputSchemas: {},
    webhookSupport: true,
    rateLimits: { requestsPerMinute: 200, burst: 40 },
    pagination: { supported: true, type: 'offset' },
    retryGuidance: { maxAttempts: 2, statusCodesToRetry: [500, 503] },
    errorMapping: { NOT_FOUND: 'Approval record not found.' },
    testConnectionOperation: 'pingApprovalCentre',
    healthCheckOperation: 'healthCheck',
    secretReferences: [],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_projects: {
    connectorKey: 'concludo_projects',
    version: '1.0.0',
    displayName: 'Concludo Projects',
    description: 'Native workspace projects, tasks, milestones, risks and decision tracker.',
    category: 'workspace_native',
    iconReference: 'FolderKanban',
    authenticationType: 'session',
    requiredScopes: ['projects:read', 'projects:write'],
    triggers: ['project.created', 'task.created', 'task.completed', 'task.overdue', 'milestone.approaching', 'milestone.delayed', 'risk.created', 'issue.created'],
    actions: ['create_project_draft', 'create_project', 'create_task', 'create_milestone', 'create_risk', 'create_issue', 'create_decision', 'create_project_status_draft'],
    inputAndOutputSchemas: {},
    webhookSupport: true,
    rateLimits: { requestsPerMinute: 300, burst: 60 },
    pagination: { supported: true, type: 'cursor' },
    retryGuidance: { maxAttempts: 3, statusCodesToRetry: [429, 500, 503] },
    errorMapping: { DUPLICATE_KEY: 'Task or project already exists.' },
    testConnectionOperation: 'pingProjectService',
    healthCheckOperation: 'healthCheck',
    secretReferences: [],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_calendar: {
    connectorKey: 'concludo_calendar',
    version: '1.0.0',
    displayName: 'Concludo Calendar',
    description: 'Native workspace calendar, deadlines, day/week/month timelines.',
    category: 'workspace_native',
    iconReference: 'Calendar',
    authenticationType: 'session',
    requiredScopes: ['calendar:read', 'calendar:write'],
    triggers: [],
    actions: ['create_calendar_draft', 'create_calendar_event'],
    inputAndOutputSchemas: {},
    webhookSupport: false,
    rateLimits: { requestsPerMinute: 300, burst: 50 },
    pagination: { supported: true, type: 'cursor' },
    retryGuidance: { maxAttempts: 3, statusCodesToRetry: [429, 500, 503] },
    errorMapping: { CONFLICT: 'Duplicate calendar event item key.' },
    testConnectionOperation: 'pingCalendarService',
    healthCheckOperation: 'healthCheck',
    secretReferences: [],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_notifications: {
    connectorKey: 'concludo_notifications',
    version: '1.0.0',
    displayName: 'Concludo Notifications',
    description: 'Internal workspace alert, email digest, and notification center.',
    category: 'workspace_native',
    iconReference: 'Bell',
    authenticationType: 'session',
    requiredScopes: ['notifications:send'],
    triggers: [],
    actions: ['create_internal_notification'],
    inputAndOutputSchemas: {},
    webhookSupport: false,
    rateLimits: { requestsPerMinute: 300, burst: 60 },
    pagination: { supported: false },
    retryGuidance: { maxAttempts: 3, statusCodesToRetry: [500, 503] },
    errorMapping: {},
    testConnectionOperation: 'pingNotifications',
    healthCheckOperation: 'healthCheck',
    secretReferences: [],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_document_reader: {
    connectorKey: 'concludo_document_reader',
    version: '1.0.0',
    displayName: 'Concludo Document Reader',
    description: 'Document extraction and text parsing engine for PDF, DOCX, and text.',
    category: 'workspace_native',
    iconReference: 'FileText',
    authenticationType: 'session',
    requiredScopes: ['documents:read'],
    triggers: ['document_reader.completed'],
    actions: ['analyse_document'],
    inputAndOutputSchemas: {},
    webhookSupport: false,
    rateLimits: { requestsPerMinute: 120, burst: 20 },
    pagination: { supported: false },
    retryGuidance: { maxAttempts: 2, statusCodesToRetry: [500] },
    errorMapping: {},
    testConnectionOperation: 'pingDocReader',
    healthCheckOperation: 'healthCheck',
    secretReferences: [],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_webhooks: {
    connectorKey: 'concludo_webhooks',
    version: '1.0.0',
    displayName: 'Concludo Webhooks',
    description: 'Inbound and outbound webhook delivery pipeline with HMAC signatures.',
    category: 'workspace_native',
    iconReference: 'Webhook',
    authenticationType: 'webhook_signature',
    requiredScopes: ['webhooks:receive', 'webhooks:publish'],
    triggers: ['webhook.received'],
    actions: ['publish_webhook'],
    inputAndOutputSchemas: {},
    webhookSupport: true,
    rateLimits: { requestsPerMinute: 600, burst: 120 },
    pagination: { supported: true, type: 'cursor' },
    retryGuidance: { maxAttempts: 3, statusCodesToRetry: [500, 502, 503, 504] },
    errorMapping: {},
    testConnectionOperation: 'pingWebhooks',
    healthCheckOperation: 'healthCheck',
    secretReferences: ['WEBHOOK_SIGNING_SECRET'],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_public_api: {
    connectorKey: 'concludo_public_api',
    version: '1.0.0',
    displayName: 'Concludo Public API',
    description: 'RESTful API gateway for programmatic workspace automation and events.',
    category: 'workspace_native',
    iconReference: 'Code',
    authenticationType: 'api_key',
    requiredScopes: ['api:events:write'],
    triggers: ['api.event_received'],
    actions: ['call_api'],
    inputAndOutputSchemas: {},
    webhookSupport: true,
    rateLimits: { requestsPerMinute: 1200, burst: 200 },
    pagination: { supported: true, type: 'offset' },
    retryGuidance: { maxAttempts: 3, statusCodesToRetry: [429, 500, 503] },
    errorMapping: {},
    testConnectionOperation: 'pingPublicApi',
    healthCheckOperation: 'healthCheck',
    secretReferences: ['CONCLUDO_API_KEY'],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
  concludo_agent_dashboard: {
    connectorKey: 'concludo_agent_dashboard',
    version: '1.0.0',
    displayName: 'Concludo Agent Dashboard',
    description: 'Operational health, execution metrics, and activity monitor.',
    category: 'workspace_native',
    iconReference: 'Activity',
    authenticationType: 'session',
    requiredScopes: ['dashboard:read'],
    triggers: ['workflow.completed', 'workflow.failed'],
    actions: ['record_audit_event'],
    inputAndOutputSchemas: {},
    webhookSupport: false,
    rateLimits: { requestsPerMinute: 300, burst: 60 },
    pagination: { supported: false },
    retryGuidance: { maxAttempts: 2, statusCodesToRetry: [500] },
    errorMapping: {},
    testConnectionOperation: 'pingDashboard',
    healthCheckOperation: 'healthCheck',
    secretReferences: [],
    revocationOperation: 'none',
    deprecationState: 'active',
  },
};
// ==========================================
// Phase 3 Initial External Connector Manifests
// ==========================================

CONNECTOR_MANIFESTS['hubspot'] = {
  connectorKey: 'hubspot',
  version: '1.0.0',
  displayName: 'HubSpot CRM',
  description: 'Enterprise CRM integration for contacts, companies, deals, pipelines, and tasks.',
  category: 'integrations',
  iconReference: 'Briefcase', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'oauth2',
  requiredScopes: ['crm.objects.contacts.read', 'crm.objects.deals.read', 'crm.objects.deals.write'],
  triggers: ['hubspot.deal_stage_changed', 'hubspot.contact_created', 'hubspot.company_created'],
  actions: ['hubspot.get_deal', 'hubspot.create_deal', 'hubspot.get_contact', 'hubspot.create_task', 'hubspot.search_records'],
  webhookSupport: true,
  rateLimits: { requestsPerSecond: 10, burstLimit: 50 },
  paginationSupport: true,
  retryGuidance: 'Exponential backoff on 429 and 5xx up to 3 attempts',
  testConnectionOperation: 'GET /crm/v3/objects/contacts?limit=1',
  healthCheckOperation: 'GET /integrations/v1/me',
  secretReferences: [],
  availabilityState: 'coming_soon',
};

CONNECTOR_MANIFESTS['stripe'] = {
  connectorKey: 'stripe',
  version: '1.0.0',
  displayName: 'Stripe Payments & Billing',
  description: 'Billing, subscription lifecycle, invoice status, and dunning workflows.',
  category: 'integrations',
  iconReference: 'CreditCard', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'api_key',
  requiredScopes: ['invoices.read', 'customers.read', 'subscriptions.read'],
  triggers: ['stripe.invoice_payment_failed', 'stripe.checkout_completed', 'stripe.subscription_created'],
  actions: ['stripe.get_invoice', 'stripe.get_customer', 'stripe.get_subscription', 'stripe.get_payment_status'],
  webhookSupport: true,
  rateLimits: { requestsPerSecond: 25, burstLimit: 100 },
  paginationSupport: true,
  retryGuidance: 'Respect Retry-After header on 429',
  testConnectionOperation: 'GET /v1/balance',
  healthCheckOperation: 'GET /v1/account',
  secretReferences: [],
  availabilityState: 'coming_soon',
};

CONNECTOR_MANIFESTS['google_sheets'] = {
  connectorKey: 'google_sheets',
  version: '1.0.0',
  displayName: 'Google Sheets',
  description: 'Read ranges, append rows, and write back task statuses with bounded batch safety.',
  category: 'integrations',
  iconReference: 'FileSpreadsheet', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'oauth2',
  requiredScopes: ['https://www.googleapis.com/auth/drive.file'],
  triggers: [],
  actions: ['google_sheets.read_range', 'google_sheets.append_row'],
  webhookSupport: false,
  rateLimits: { requestsPerSecond: 5, burstLimit: 20 },
  paginationSupport: true,
  retryGuidance: 'Exponential backoff with jitter on 429',
  testConnectionOperation: 'GET https://www.googleapis.com/drive/v3/about?fields=user',
  healthCheckOperation: 'GET https://www.googleapis.com/drive/v3/about?fields=user',
  secretReferences: [],
  availabilityState: 'coming_soon',
};

CONNECTOR_MANIFESTS['google_calendar'] = {
  connectorKey: 'google_calendar',
  version: '1.0.0',
  displayName: 'Google Calendar',
  description: 'External calendar synchronisation for events, drafts, and meeting invites.',
  category: 'integrations',
  iconReference: 'Calendar', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'oauth2',
  requiredScopes: ['https://www.googleapis.com/auth/calendar.events'],
  triggers: [],
  actions: ['google_calendar.create_event'],
  webhookSupport: true,
  rateLimits: { requestsPerSecond: 10, burstLimit: 30 },
  paginationSupport: true,
  retryGuidance: 'Exponential backoff',
  testConnectionOperation: 'GET https://www.googleapis.com/calendar/v3/calendars/primary/events?maxResults=1',
  healthCheckOperation: 'GET https://www.googleapis.com/calendar/v3/calendars/primary/events?maxResults=1',
  secretReferences: [],
  availabilityState: 'coming_soon',
};

CONNECTOR_MANIFESTS['google_drive'] = {
  connectorKey: 'google_drive',
  version: '1.0.0',
  displayName: 'Google Drive',
  description: 'Cloud document retrieval and file storage for workspace outputs.',
  category: 'integrations',
  iconReference: 'HardDrive', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'oauth2',
  requiredScopes: ['https://www.googleapis.com/auth/drive.file'],
  triggers: [],
  actions: ['google_drive.save_file'],
  webhookSupport: true,
  rateLimits: { requestsPerSecond: 10, burstLimit: 30 },
  paginationSupport: true,
  retryGuidance: 'Exponential backoff',
  testConnectionOperation: 'GET https://www.googleapis.com/drive/v3/about?fields=user',
  healthCheckOperation: 'GET https://www.googleapis.com/drive/v3/about?fields=user',
  secretReferences: [],
  availabilityState: 'coming_soon',
};

CONNECTOR_MANIFESTS['microsoft_outlook'] = {
  connectorKey: 'microsoft_outlook',
  version: '1.0.0',
  displayName: 'Microsoft Outlook (Graph)',
  description: 'Microsoft 365 Exchange mail triggers and approved external correspondence.',
  category: 'integrations',
  iconReference: 'Mail', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'oauth2',
  requiredScopes: ['Mail.Send'],
  triggers: [],
  actions: ['microsoft_outlook.send_approved_email'],
  webhookSupport: true,
  rateLimits: { requestsPerSecond: 10, burstLimit: 40 },
  paginationSupport: true,
  retryGuidance: 'Exponential backoff on 429',
  testConnectionOperation: 'GET https://graph.microsoft.com/v1.0/me',
  healthCheckOperation: 'GET https://graph.microsoft.com/v1.0/me',
  secretReferences: [],
  availabilityState: 'coming_soon',
};

CONNECTOR_MANIFESTS['slack'] = {
  connectorKey: 'slack',
  version: '1.0.0',
  displayName: 'Slack Enterprise',
  description: 'Channel alerts, incident notifications, and human approval reminders.',
  category: 'integrations',
  iconReference: 'MessageSquare', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'oauth2',
  requiredScopes: ['chat:write', 'channels:read'],
  triggers: ['slack.message_posted'],
  actions: ['slack.post_message', 'slack.post_incident_alert'],
  webhookSupport: true,
  rateLimits: { requestsPerSecond: 1, burstLimit: 5 },
  paginationSupport: true,
  retryGuidance: 'Tier 3 rate limit backoff',
  testConnectionOperation: 'GET /api/auth.test',
  healthCheckOperation: 'GET /api/auth.test',
  secretReferences: [],
  availabilityState: 'coming_soon',
};

CONNECTOR_MANIFESTS['custom_api'] = {
  connectorKey: 'custom_api',
  version: '1.0.0',
  displayName: 'Custom REST API Connector',
  description: 'Connect any external REST/JSON service under strict URL allowlist and SSRF controls.',
  category: 'developer',
  iconReference: 'Globe', inputAndOutputSchemas: {}, pagination: { supported: true }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'bearer',
  requiredScopes: ['api:call'],
  triggers: [],
  actions: ['custom_api.call_get', 'custom_api.call_post', 'custom_api.call_put'],
  webhookSupport: false,
  rateLimits: { requestsPerSecond: 10, burstLimit: 20 },
  paginationSupport: true,
  retryGuidance: 'Configurable retry policy',
  testConnectionOperation: 'HEAD /',
  healthCheckOperation: 'HEAD /',
  secretReferences: ['vault:custom_api_secret'],
  availabilityState: 'available',
};

CONNECTOR_MANIFESTS['custom_webhook'] = {
  connectorKey: 'custom_webhook',
  version: '1.0.0',
  displayName: 'Custom Inbound Webhook',
  description: 'Receive verified HMAC/token webhooks from external systems.',
  category: 'developer',
  iconReference: 'Webhook', inputAndOutputSchemas: {}, pagination: { supported: false }, errorMapping: {}, revocationOperation: '', deprecationState: 'active',
  authenticationType: 'webhook_hmac',
  requiredScopes: ['webhook:receive'],
  triggers: ['custom_webhook.received'],
  actions: [],
  webhookSupport: true,
  rateLimits: { requestsPerSecond: 50, burstLimit: 200 },
  paginationSupport: false,
  retryGuidance: 'Immediate acknowledgment with 202 Accepted',
  testConnectionOperation: 'POST /health',
  healthCheckOperation: 'POST /health',
  secretReferences: ['vault:webhook_hmac_secret'],
  availabilityState: 'available',
};

export function syncConnectorAvailability(providers: Array<{ id: string; availability: string }>) {
  for (const p of providers) {
    if (CONNECTOR_MANIFESTS[p.id]) {
      CONNECTOR_MANIFESTS[p.id].availabilityState = p.availability;
    }
  }
}
